### ISSUE TITLE
ERROR 403: Forbidden when dowloading data

### ISSUE THREAD

**Issue by rth** [ramp-kits/solar_wind#16]
Running `python download_data.py` currently produces,
```
Downloading from https://storage.ramp.studio/solar_wind/data_train.parquet ...
[...]
  File "/home/rth/.miniconda3/envs/solar-wind-env/lib/python3.6/urllib/request.py", line 650, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 403: Forbidden
````

I get the same error by tried to download that file via wget. It wasn't the case a few weeks ago.

Do we know if some permissions changed at storage.ramp.studio ? cc @glemaitre

**Comment by glemaitre** [comment]
@kegl Do you know if we need to mount the disk or something like this.
It will be annoying if people cannot download the data.

**Comment by frcaud** [comment]
@rth @glemaitre New download_data script takes data from OSF

**Comment by rth** [comment]
OK, thanks! Let's close then.
