### ISSUE TITLE
Conflict in imbalanced-learn dependencies

### ISSUE THREAD

**Issue by aboucaud** [ramp-kits/solar_wind#8]
Hey @jorisvandenbossche & @glemaitre ,

When I try to set up the AMI, my installation script runs into an issue 
when installing the dependencies from the `ami_environment.yml`.
```
UnsatisfiableError: The following specifications were found to be in conflict:
  - imbalanced-learn -> scikit-learn=0.19
  - scikit-learn[version='>=0.20']
```
Could you solve that, please?

**Comment by jorisvandenbossche** [comment]
Hopefully solved with https://github.com/ramp-kits/solar_wind/commit/55fb953c68c6c8a1c6ffdf2a1be1de5bd5ac960b, can you try again?

**Comment by aboucaud** [comment]
Conflict fixed. Thanks.
